(() => {
  const kh = window.KatanaHelpers = window.KatanaHelpers || {};

  kh.constants = {
    DEBUG: false,
    KEYS: {
      TOTAL: "kh_clicks_total",
      BY_DATE: "kh_clicks_by_date",
      RETURN_URL: "kh_return_url",
      SO_TIMERS: "kh_so_timer_state",
      SUPPLIER_BUTTONS: "kh_supplier_buttons",
    },
    IDS: {
      STYLE: "kh-style",
      HUD: "kh-hud",
      MO_TIMER: "kh-mo-timer",
      TOAST: "kh-toast",
      BTN_CREATE_MO: "kh-create-mo-btn",
      BTN_CREATE_PO: "kh-create-po-btn",
      BTN_STATUS_HELPER: "kh-status-helper-btn",
      BTN_MO_DONE_RETURN: "kh-mo-done-return-btn",
      WRAP_MO_DONE_RETURN: "kh-mo-done-return-wrap",
      BTN_ETSY_ORDER: "kh-etsy-order-btn",
      ETSY_ORDER_CELL: "kh-etsy-order-cell",
      BTN_PO_SUPPLIER: "kh-po-supplier-btn",
      WRAP_PO_SUPPLIER: "kh-po-supplier-wrap",
      BTN_PO_SUPPLIER_EDIT: "kh-po-supplier-edit-btn",
      PO_SUPPLIER_MODAL: "kh-po-supplier-modal",
      BTN_SIMPLYPRINT_NAV: "kh-simplyprint-nav-btn",
    },
    CLASSES: {
      LABEL_MO_DONE_RETURN: "kh-mo-done-return-label",
      BTN_SO_EX: "kh-so-ex-btn",
      ETSY_ORDER_CELL: "kh-etsy-order-cell",
      PO_SUPPLIER_BTN: "kh-po-supplier-btn",
      PO_SUPPLIER_WRAP: "kh-po-supplier-wrap",
      PO_SUPPLIER_EDIT: "kh-po-supplier-edit",
      PO_SUPPLIER_MODAL: "kh-po-supplier-modal",
      PO_SUPPLIER_MODAL_CONTENT: "kh-po-supplier-modal-content",
      PO_SUPPLIER_MODAL_ROW: "kh-po-supplier-modal-row",
      PO_SUPPLIER_MODAL_WARNING: "kh-po-supplier-modal-warning",
      PO_SUPPLIER_MODAL_ACTIONS: "kh-po-supplier-modal-actions",
      SIMPLYPRINT_NAV: "kh-simplyprint-nav-btn",
    },
    SELECTORS: {
      CREATE_BTN: 'button[data-testid="globalAddButton"]',
      MO_ITEM: 'a[data-testid="globalAddManufacturing"]',
      PO_ITEM: 'a[data-testid="globalAddPurchase"]',
      NAV_ITEMS_BTN: '[data-testid="MainNavigationPortfolio"]',
      ENTITY_STATUS_BTN: 'button[data-testid="menuButton-entityStatus"]',
      MO_STATUS_DONE_ITEM: 'li[data-testid="menuListItem-entityStatus-done"]',
      SO_STATUS_PACK_ALL_ITEM: 'li[data-testid="menuListItem-entityStatus-packAll"]',
      DIALOG_TITLE: 'div[role="dialog"] h2',
      DIALOG_CLOSE_BTN: 'div[role="dialog"] button#closeButton',
      SO_ROW_ACTIONS_BTN: 'button[data-testid="soRowActionsMenu-button"]',
      SO_MENU_MAKE_IN_BATCH: 'li[data-testid="soRowActionsMenu-item-makeInBatch"]',
      BATCH_QTY_INPUT: 'input[data-testid="singleMOLayoutQuantityInput"]',
      CREATE_AND_OPEN: 'button[data-testid="createAndOpenOrderButton"]',
      HEADER_SALES_ORDER: '[data-testid="headerNameSALESORDER"]',
      SO_ORDER_FIELD: ".soOrderNo",
      SO_ORDER_INPUT: 'input[name="orderNo"]',
    },
    GRID: {
      INGREDIENTS_ID: "#ingredients-grid",
      AVAILABILITY_COL_ID: "availability3",
    },
    URLS: {
      ETSY_ORDER: "https://www.etsy.com/your/orders/sold",
      SIMPLYPRINT_PANEL: "https://simplyprint.io/panel/printers",
      SIMPLYPRINT_ICON: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://simplyprint.io/favicon.ico&size=64",
    },
    CONFIG: {
      DOUBLE_CLICK_WINDOW_MS: 250,
      SAVED_CLICKS_EX_NORMAL: 4,
      SAVED_CLICKS_ULTRA_EXTRA: 2,
      ULTRA_MAX_WAIT_FOR_READY_MS: 7000,
      ULTRA_READY_POLL_MS: 140,
      ULTRA_READY_COUNTDOWN_THRESHOLD_MS: 1500,
      ULTRA_WAIT_GRID_MS: 20000,
      ULTRA_SCAN_TIMEOUT_MS: 30000,
      PO_SUPPLIER_BUTTON_BG: "#2563eb",
      PO_SUPPLIER_BUTTON_TEXT: "#fff",
      PO_SUPPLIER_BUTTON_DISABLED_BG: "#e2e8f0",
      PO_SUPPLIER_BUTTON_DISABLED_TEXT: "#64748b",
    },
  };
})();
